
import {
    getGlobalCloudStats,
    getDetailedAnalytics,
    getReclaimableAccounts
} from './database';
import fs from 'fs';
import path from 'path';

export async function generateReport(operatorAddress: string) {
    console.log(`\n📊 Generating Operator Report for ${operatorAddress}...\n`);

    try {
        const stats: any = await getDetailedAnalytics(operatorAddress);
        const reclaimable = await getReclaimableAccounts(operatorAddress);

        // Calculate Efficiency Metrics
        const invested = stats.total_reclaimed_lamports || 0;
        const recovered = stats.realized_rent || 0;

        const efficiency = invested > 0
            ? ((recovered / invested) * 100).toFixed(1)
            : "0.0";

        const reclaimableSol = reclaimable.reduce((sum, acc) => sum + acc.rentPaid, 0) / 1e9;

        const report = `
# 📜 KoraScan Operator Report Card
**Date**: ${new Date().toISOString().split('T')[0]}
**Operator**: ${operatorAddress}

---

## 🚀 Performance Summary

| Metric | Value | Grade |
| :--- | :--- | :--- |
| **Efficiency Score** | **${efficiency}%** | ${getGrade(parseFloat(efficiency))} |
| **Total Reclaimed** | ${SOL(recovered)} | - |
| **Pending Reclaim** | ${reclaimableSol.toFixed(4)} SOL | - |
| **Tx Count** | ${stats.tx_count || 0} | - |

---

## 💰 Treasury Impact

*   **Total Rent Invested**: ${SOL(invested)}
*   **Net Profit (Realized)**: ${SOL(recovered)}
*   **Costs (Fees)**: ${SOL(stats.total_fees_lamports)}
*   **ROI**: ${stats.total_fees_lamports > 0 ? ((recovered / stats.total_fees_lamports) * 100).toFixed(0) : "∞"}%

---

## 🔍 Discovery Insights

*   **Total Accounts Tracked**: ${stats.total_accounts}
*   **Unique Users Served**: ${stats.unique_users}
*   **Active (Unclaimed)**: ${stats.active_count}
*   **Locked (Unauthorized)**: ${stats.locked_count}

## 🏆 Top Leak Sources (Top 5 Mints)
${stats.top_mints.slice(0, 5).map((m: any, i: number) => `${i + 1}. **${m.mint.slice(0, 4)}...${m.mint.slice(-4)}**: ${m.count} accounts`).join('\n')}

---

*Generated by KoraScan Sidecar v1.0.4*
`;

        // Output to Console
        console.log(report);

        // Save to File
        const filename = `report_${new Date().toISOString().split('T')[0]}.md`;
        fs.writeFileSync(path.join(process.cwd(), filename), report);
        console.log(`\n✅ Report saved to: ${filename}`);

    } catch (e: any) {
        console.error("Failed to generate report:", e.message);
    }
}

function SOL(lamports: number): string {
    return (lamports / 1e9).toFixed(4) + " SOL";
}

function getGrade(score: number): string {
    if (score >= 95) return "A+ 💎";
    if (score >= 90) return "A 🔥";
    if (score >= 80) return "B 👍";
    if (score >= 70) return "C";
    return "Needs Work ⚠️";
}
